# Generated by Django 4.2.29 on 2026-04-02 14:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.issue_cover_path),
        ),
    ]
