# Generated by Django 4.2.29 on 2026-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_issue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
