# Generated by Django 4.2.29 on 2026-04-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_issue_isbn_alter_issue_issue_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='synopsis',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
