# Generated by Django 4.2.29 on 2026-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collectionitem_physical_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='original_content',
            field=models.CharField(blank=True, default='', help_text='Edição original em que o conteúdo foi publicado (ex: Nightwing (2016) 101-105). Apenas quadrinhos.', max_length=255, null=True),
        ),
    ]
